# ======================================================================
# Github Actions script used to deploy webpage to ekarton.github.io
# Refer to https://github.com/features/actions for more info
# ======================================================================

name: Deploy to Github Pages
on: 
  push:
    branches:
      - main
jobs:
  update-gh-pages-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./src
